version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulse-app
    networks: [pulse, infra]
    env_file:
      - ./configs/.env

networks:
  pulse:
  infra:
    external: true      # assumes `docker network create infra` already exists
